### ISSUE TITLE
Feature Request - Disable updating/setting scope to site

### ISSUE THREAD

**Issue by brandan-schmitz** [netboxlabs/orb-agent#100]
When an IP is collected from a switch it creates/updates the prefix that IP belongs to. We have many prefixes that go to multiple sites, and so when a switch that is set to a different site is polled, it changes the scope on the prefix to that site. It would be nice to be able to make it so that the site is not set as the scope for things such as the Prefix. It seems that currently the VLANs do not have this behavior and it would be nice if the prefix did not either.

Take the following configuration for example. I have two switches, one at `Site 1` and one at `Site 2`. I have an IP from the same prefix (192.168.206.0/24) assigned to each switch. I have already created this prefix in Netbox, but now when the agent runs, it will update my prefix and it will show the scope for that prefix as either `Site 1` or `Site 2` depending on what was last returned. Sometimes it switches based on when the agent polls the switch.

```yaml
orb:
  config_manager:
    active: local
  backends:
    device_discovery:
    common:
      diode:
        target: grpc://localhost:8080/diode
        client_id: ${DIODE_USERNAME}
        client_secret: ${DIODE_PASSWORD}
        agent_name: agent-01
  policies:
    device_discovery:
      site1_switches:
        config:
          schedule: "* * * * *"
          defaults:
            site: Site 1
            role: Switching
        scope:
          - hostname: 192.168.206.50
            driver: ios
            username: ${SWITCH_USERNAME}
            password: ${SWITCH_PASSWORD}
            optional_args:
              secret: ${ENABLE_PASSWORD}
      site2_switches:
        config:
          schedule: "* * * * *"
          defaults:
            site: Site 2
            role: Switching
        scope:
          - hostname: 192.168.206.51
            driver: ios
            username: ${SWITCH_USERNAME}
            password: ${SWITCH_PASSWORD}
            optional_args:
              secret: ${ENABLE_PASSWORD}
```
