### ISSUE TITLE
Feature Request - Ability to set configs on a per-scoped device basis

### ISSUE THREAD

**Issue by brandan-schmitz** [netboxlabs/orb-agent#101]
The ability to set things such as the role, or manually specify a device type would be a really useful feature. We would ideally like to be able to create a policy for each of our sites. Currently we have multiple device roles at the same site, and this would require us to create multiple policies per site and add the different devices to the scopes for a different policy.

Another thing that would be useful would be to override the type of device that is returned. For example, we have a 10gig Cisco 4948 switch, and the device type returned by the agent is `Cisco WS-C4948-10GE`. However it is more commonly known as a `Cisco Catalyst 4948-10GE` and when you import devices from the Netbox devicetype-library, it also creates it a the `Cisco Catalyst 4948-10GE`. In cases like this it would be nice to be able to override that type because if you simply modify it in Netbox, the next time the device is polled by the agent it is changed back.

A config such as this would be nice to be able to do:
```yaml
orb:
  config_manager:
    active: local
  backends:
    device_discovery:
    common:
      diode:
        target: grpc://localhost.com:8080/diode
        client_id: ${DIODE_USERNAME}
        client_secret: ${DIODE_PASSWORD}
        agent_name: agent-01
  policies:
    device_discovery:
      office_1:
        config:
          schedule: "* * * * *"
          defaults:
            site: Office 1
            role: Switching
        scope:
          - driver: ios
            hostname: 192.168.206.66
            username: ${USERNAME}
            password: ${PASSWORD}
            optional_args:
              secret: ${ENABLE_PASSWORD}
          - driver: ios
            hostname: 192.168.206.67
            username: ${USERNAME}
            password: ${PASSWORD}
            optional_args:
              secret: ${ENABLE_PASSWORD}
          - driver: ios
            hostname: 192.168.206.68
            username: ${USERNAME}
            password: ${PASSWORD}
            optional_args:
              secret: ${ENABLE_PASSWORD}
            override_defaults:
              role: Video
```

**Comment by brandan-schmitz** [comment]
Moving to proper repository.

**Comment by leoparente** [comment]
This is the proper repo for this. so I will reopen it here @brandan-schmitz . Thanks for reporting it

**Comment by leoparente** [comment]
hi @brandan-schmitz. Both request capabilities were added to latest develop; https://github.com/netboxlabs/orb-agent/blob/develop/docs/backends/device_discovery.md

please pull it and check if covers your usecase

```
docker pull  netboxlabs/orb-agent:develop
```

A sample that overrides device_type and defaults:

```
....
policies:
    device_discovery:
      office_1:
        config:
          schedule: "* * * * *"
          defaults:
            site: Office 1
            role: Switching
            device:
               model: Cisco Catalyst 4948-10GE
        scope:
          - driver: ios
            hostname: 192.168.206.67
            username: ${USERNAME}
            password: ${PASSWORD}
            optional_args:
              secret: ${ENABLE_PASSWORD}
          - driver: ios
            hostname: 192.168.206.68
            username: ${USERNAME}
            password: ${PASSWORD}
            optional_args:
              secret: ${ENABLE_PASSWORD}
            override_defaults:
              role: Video
```
