### ISSUE TITLE
Feature Request - Device Discovery: Add Defaults Capability to Scope Section

### ISSUE THREAD

**Issue by Kramdin-thinklogistics** [netboxlabs/orb-agent#109]
As an interim, or perhaps additional feature, to what others are asking in terms of dynamic device discovery (I too think this is needed), it would make the configuration easier/cleaner if we could specify common device defaults and then in-line overrides where needed (similar to the network_discovery section). 

For example, if there are many ios devices, all being queried using the same user/password (i.e. RADIUS credentials), all using the same optional_args, we could simplify by using syntax similar to this (vs the repeated entries currently required):

`device_discovery:`
`  scope:`
`     defaults:`
`            driver: ios`
`            username: xxxxxxx`
`            password: xxxxxxx`
`            optional_args:`
`                canonical_int: True`
`                force_no_enable: True`
`    targets:`
`        - host1`
`        - host2`
`        - host3`
`        - host4`
`        - host5`
`            driver: something_else`
`            username: yyyyyyy`
`            password: yyyyyyy`

**Comment by leoparente** [comment]
hi @Kramdin-thinklogistics. YAML has a feature of Anchors and Aliases that we can take advantage and is better than doing a custom implementation for it. you can reuse A config like this:

```yaml
orb:
  ...
  policies:
    device_discovery:
      discovery_1:
        credentials: &ios_credentials
          username: admin
          password: ${PASS}
          driver: ios
          optional_args:
            canonical_int: True
            force_no_enable: True
        config:
          defaults:
            site: my site
            tenant: my tenant
        scope:
          - hostname: host1
            <<: *ios_credentials
          - hostname: host2
            <<: *ios_credentials
          - hostname: host5
            driver: something_else
            username: yyyyyyy
            password: yyyyyyy
```

We just added a PR with this explanation as well: https://github.com/netboxlabs/orb-agent/pull/124
