### ISSUE TITLE
Orb Agent Network Discovery for the hostname

### ISSUE THREAD

**Issue by sean12345-1** [netboxlabs/orb-agent#118]
I can't seem to find a way to have the orb agent get the host name of each of the ip that it located. Is that a function of the network discovery side.

**Comment by leoparente** [comment]
For now, it should be adding hostname in the comments like this: 

![Image](https://github.com/user-attachments/assets/b59d8ae1-74c4-45a2-a803-46b1db507897)

**Comment by sean12345-1** [comment]
@leoparente is there a config that I need to set to have it put that information in the comments spot?

**Comment by leoparente** [comment]
``1. use orb-agent develop image for now. This change was not released yet.
2. do not add any comments in the default section. If there is no comment defined by the user, the code will fill comments section with the above infomation

I saw that you have this:

```
...
      defaults:
        comments: none
        description: IP discovered by network discovery
        tags: [net-discovery, orb-agent]

```

so you need to remove comments
```
...
      defaults:
        description: IP discovered by network discovery
        tags: [net-discovery, orb-agent]

```
