### ISSUE TITLE
Cannot use custom driver with latest version of Orb-Agent

### ISSUE THREAD

**Issue by celeroncool** [netboxlabs/orb-agent#58]
Hello!

Trying to use https://github.com/napalm-automation-community/napalm-aruba-cx to get configs from our Aruba CX6000 switches.
But every time I try to use the device discovery, it ends up with this error.

`{"level":"warn","ts":"2025-01-30T11:47:18.823Z","caller":"policyMgr/manager.go:197","msg":"policy failed to apply","policy_id":"","policy_name":"aos_test","error":"400 Policy aos_test, Hostname 10.213.4.24: specified driver 'aoscx' was not found in the current installed drivers list: ['ios', 'eos', 'junos', 'nxos']."}`

Contents of drivers.txt:
```
napalm-aruba-cx
pyaoscx
requests
urllib3
```

Contents of agent.yaml
```
version: "1.0"

visor:
  taps:

orb:
  config_manager:
   active: local
  backends:
    device_discovery:
    network_discovery:
    common:
      diode:
        target: grpc://localhost:8080/diode
        api_key: ${DIODE_API_KEY}
        agent_name: netbox-qa-01
  policies:
    network_discovery:
      aos_vlan1:
        config:
          schedule: "*/5 * * * *"
          timeout: 5
          defaults:
            description: IP discovered by network discovery
        scope:
          targets: [192.168.3.0/24]
    device_discovery:
      aos_test:
        config:
          schedule: "*/5 * * * *"
          defaults:
            site: xxxx
        scope:
          - driver: aoscx
            hostname: 10.213.4.24
            username: xxx
            password: xxx
```

Output from console:
```
Installing additional drivers
Collecting napalm-aruba-cx (from -r /opt/orb/drivers.txt (line 1))
  Downloading napalm_aruba_cx-0.1.4-py3-none-any.whl.metadata (3.9 kB)
Collecting pyaoscx (from -r /opt/orb/drivers.txt (line 2))
  Downloading pyaoscx-2.6.0-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.12/site-packages (from -r /opt/orb/drivers.txt (line 3)) (2.32.3)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/site-packages (from -r /opt/orb/drivers.txt (line 4)) (2.3.0)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/site-packages (from pyaoscx->-r /opt/orb/drivers.txt (line 2)) (6.0.2)
Requirement already satisfied: netaddr in /usr/local/lib/python3.12/site-packages (from pyaoscx->-r /opt/orb/drivers.txt (line 2)) (1.3.0)
Collecting requests-toolbelt (from pyaoscx->-r /opt/orb/drivers.txt (line 2))
  Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Collecting wheel (from pyaoscx->-r /opt/orb/drivers.txt (line 2))
  Using cached wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.12/site-packages (from requests->-r /opt/orb/drivers.txt (line 3)) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/site-packages (from requests->-r /opt/orb/drivers.txt (line 3)) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/site-packages (from requests->-r /opt/orb/drivers.txt (line 3)) (2024.7.4)
Downloading napalm_aruba_cx-0.1.4-py3-none-any.whl (15 kB)
Downloading pyaoscx-2.6.0-py3-none-any.whl (179 kB)
Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
Using cached wheel-0.45.1-py3-none-any.whl (72 kB)
Installing collected packages: wheel, napalm-aruba-cx, requests-toolbelt, pyaoscx
Successfully installed napalm-aruba-cx-0.1.4 pyaoscx-2.6.0 requests-toolbelt-1.0.0 wheel-0.45.1
```
