### ISSUE TITLE
Feature request - tenant/site config for agent

### ISSUE THREAD

**Issue by sepetuks** [netboxlabs/orb-agent#81]
We have multiple customers in separate L2 domains/VRFs.
Any of them can use same subnet in their network (kind of duplicate prefixes)
Would it be possible to have config parameter for agent that it explicitly define for which tenant/site this agent is collecting data? Or maybe VRF?

**Comment by leoparente** [comment]
hi @sepetuks we are currently working to support more data models on diode SDK. Therefore, it will improve the supported netbox types on orb-agent and its backends. If applicable for your use case, a temporary solution would be to add this information as Tags in the agent policy : https://github.com/netboxlabs/orb-agent/blob/develop/docs/backends/network_discovery.md#defaults

**Comment by sepetuks** [comment]
> hi [@sepetuks](https://github.com/sepetuks) we are currently working to support more data models on diode SDK. Therefore, it will improve the supported netbox types on orb-agent and its backends. If applicable for your use case, a temporary solution would be to add this information as Tags in the agent policy : https://github.com/netboxlabs/orb-agent/blob/develop/docs/backends/network_discovery.md#defaults

Hi, thanks for proposal but that will not solve issue if same subnets are being used in 2 different VRFs. Netbox will not be able to distinguish into which one to assign collected data. So I just need to wait untill data models are expanded.

**Comment by Marcussjogren** [comment]
> > hi [@sepetuks](https://github.com/sepetuks) we are currently working to support more data models on diode SDK. Therefore, it will improve the supported netbox types on orb-agent and its backends. If applicable for your use case, a temporary solution would be to add this information as Tags in the agent policy : https://github.com/netboxlabs/orb-agent/blob/develop/docs/backends/network_discovery.md#defaults
> 
> Hi, thanks for proposal but that will not solve issue if same subnets are being used in 2 different VRFs. Netbox will not be able to distinguish into which one to assign collected data. So I just need to wait untill data models are expanded.

What you probably could do is to tag them in the orb agent, and then have a script running that looks for tag "customer1" and then checking if the address has "customer1" configured as tenant. If not, it will add it.

But thats just a workaround until proper modelling of Diode data has been developed.

**Comment by sepetuks** [comment]
if I use following config:
```
network_discovery:
  policy_1:
    config:
      defaults:
        tenant: Customer 1
        vrf: VRF1
      schedule: "*/5 * * * *"
      timeout: 5
    scope:
      targets:
         - 10.10.10.0/24
         - 10.10.10.254
 ```

The defaults are not passed to diode server. The data load simply do not get that data,
based on code https://github.com/netboxlabs/orb-discovery/blob/develop/network-discovery/config/config.go#L53 it looks it should be possible to pass vrf and tenant?

**Comment by leoparente** [comment]
hi @sepetuks can you try to pull latest develop image with `docker pull netboxlabs/orb-agent:develop` and run agent using this image to validate this feature?

**Comment by sepetuks** [comment]
It looks there is still some errors:

- For some reason it also tries to populate data where RD is also same as VRF name. Which is not expected behavior. I would expect only VRF name to be passed. Now result was that new VRF was created.
- Another issue with tenant: my tenant has required custom field and I get error because required data was not provided (for custom field)

**Comment by drive16** [comment]
> It looks there is still some errors:
> 
> * For some reason it also tries to populate data where RD is also same as VRF name. Which is not expected behavior. I would expect only VRF name to be passed. Now result was that new VRF was created.
> * Another issue with tenant: my tenant has required custom field and I get error because required data was not provided (for custom field)

I would like to share my experience, especially regarding the first point: today I was running Diode for network discovery and, despite having specified an already existing VRF in Netbox in the agent.yaml file, once the ingestion completed I found in Netbox that a new VRF was created.
The new VRF had the same name as the existing one, plus the RD (which was not specified in the already existing one) with the same string as the VRF name.

**Example**:
Existing VRF: test
VRF created after using Diode: test (test)

I tried to modify the already existing VRF by specifying a unique RD, and then I modified the agent.yaml file by setting the RD in the defaults.vrf field. 
The result was unexpected: Orb overrode the existing VRF by changing its name to the one specified in the RD. But at least, in this case, the network discovery put the IP addresses in the correct VRF.

It would be nice to have the discovery place the IP addresses in the same VRF as specified in defaults.vrf, without creating new VRFs every time or overriding them.

**Comment by leoparente** [comment]
hi @sepetuks and @drive16. VRF duplicates seems to be fixed in latest diode and diode plugin versions. And with that we removed that wrong idea of ingesting RD value in network discovery to force uniqueness.

so give a try with:
[diode-netbox-plugin](https://github.com/netboxlabs/diode-netbox-plugin) v1.13.0
[Diode](https://github.com/netboxlabs/diode) v2.0.0

Then try to pull latest develop image with `docker pull netboxlabs/orb-agent:develop` and run agent using this image.

network discovery should be v1.18.0, so in the agent logs you must see:

````
"network-discovery readiness ok, got version":"1.18.0"  
````

**Comment by lukassavukaitis** [comment]
Hi @leoparente, I've just tried that with latest diode server + diode plugin and develop orb image, however I'm still hitting same duplicate VRF issue.
If my policy looks like this (rd for VRF not declared) -
```
device_discovery:
  discovery_1:
    config:
      defaults:
        site: "Some Site"
        role: "LAN Switch"
        description: "Diode ingestion"
        device:
          model: Catalyst 2960X-48FPD-L
          manufacturer: Cisco
          asset_tag: "Some Asset Tag"
        tenant: 
          name: "Some Tenant"
          group: "Some Tenant Group"
        ipaddress:
          vrf:
			name: "MyVRF"
        vlan:
          group: "Some VLAN group"
    scope:
      - driver: ios
        hostname: 10.20.30.40
        username: ${NETWORK_SERVICE_ACCOUNT}
        password: ${NETWORK_SERVICE_ACCOUNT_PASSWORD}
```
it will then create a new VRF and won't pick the existing one.

I also tried something like this -
```
vrf:
    name: "MyVRF"
    rd: 
```
however it didn't work either and created a new VRF instead of picking an existing one (in Netbox, I don't have rd defined for VRF too)

If I add an rd value in Netbox and put the same rd in policy, it works fine.

P.S. When VRF is created by diode, it doesn't add rd value to VRF too (which is totally fine).

**Comment by leoparente** [comment]
hi @lukassavukaitis. if you run the agent/policy multiple times, are you getting a new VRF each run?

**Comment by drive16** [comment]
> hi [@sepetuks](https://github.com/sepetuks) and [@drive16](https://github.com/drive16). VRF duplicates seems to be fixed in latest diode and diode plugin versions. And with that we removed that wrong idea of ingesting RD value in network discovery to force uniqueness.
> 
> so give a try with: [diode-netbox-plugin](https://github.com/netboxlabs/diode-netbox-plugin) v1.13.0 [Diode](https://github.com/netboxlabs/diode) v2.0.0
> 
> Then try to pull latest develop image with `docker pull netboxlabs/orb-agent:develop` and run agent using this image.
> 
> network discovery should be v1.18.0, so in the agent logs you must see:
> 
> ```
> "network-discovery readiness ok, got version":"1.18.0"  
> ```

Hello @leoparente,

In my case it worked perfectly, using network-discovery v1.18.0 and the latest version from Netbox and Diode.

For reference, here is the agent.yaml file I used:
```
orb:
  config_manager:
    active: local
  backends:
    network_discovery:
    common:
      diode:
        target: grpc://localhost:8080/diode
        client_id: ${DIODE_CLIENT_ID}
        client_secret: ${DIODE_CLIENT_SECRET}
        agent_name: diode-ingest
  policies:
    network_discovery:
      network_scan:
        config:
          # schedule: "0 */6 * * *"
          timeout: 5
          defaults:
            tenant: my_tenant
            description: Added by Diode
            vrf: "my_vrf"
            tags: [network-discovery]
        scope:
          fast_mode: true
          targets:
            - 192.0.0.0/24

```

Thanks!
